# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(0, 0, 881, 561))
        self.frame1.setAutoFillBackground(False)
        self.frame1.setStyleSheet("background-color: rgb(40, 43, 48);\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setGeometry(QtCore.QRect(170, 20, 691, 531))
        self.frame2.setAutoFillBackground(False)
        self.frame2.setStyleSheet("background-color: rgb(30, 32, 34);\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.URL = QtWidgets.QTextEdit(self.frame2)
        self.URL.setGeometry(QtCore.QRect(80, 60, 511, 31))
        self.URL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.URL.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.URL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.URL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.URL.setObjectName("URL")
        self.SUBMIT = QtWidgets.QPushButton(self.frame2)
        self.SUBMIT.setGeometry(QtCore.QRect(600, 60, 81, 31))
        self.SUBMIT.setStyleSheet("QPushButton {\n"
"transition: all .5s ease;\n"
"color:white;\n"
"    font: 75 11pt \"Chilanka\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"border:1px solid white;\n"
"text-transform: uppercase;\n"
"text-align: center;\n"
"line-height: 1;\n"
"background-color :rgb(0, 119, 248);\n"
"\n"
"outline: none;  \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(24, 33, 62);\n"
"    background-color: white;;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.SUBMIT.setIconSize(QtCore.QSize(40, 40))
        self.SUBMIT.setObjectName("SUBMIT")
        self.title = QtWidgets.QTextEdit(self.frame2)
        self.title.setEnabled(False)
        self.title.setGeometry(QtCore.QRect(80, 140, 511, 31))
        self.title.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.title.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.title.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.title.setUndoRedoEnabled(True)
        self.title.setObjectName("title")
        self.views = QtWidgets.QTextEdit(self.frame2)
        self.views.setEnabled(False)
        self.views.setGeometry(QtCore.QRect(80, 190, 151, 31))
        self.views.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.views.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.views.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.views.setObjectName("views")
        self.length = QtWidgets.QTextEdit(self.frame2)
        self.length.setEnabled(False)
        self.length.setGeometry(QtCore.QRect(80, 240, 141, 31))
        self.length.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.length.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.length.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.length.setObjectName("length")
        self.rating = QtWidgets.QTextEdit(self.frame2)
        self.rating.setEnabled(False)
        self.rating.setGeometry(QtCore.QRect(80, 290, 151, 31))
        self.rating.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rating.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.rating.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rating.setObjectName("rating")
        self.status = QtWidgets.QTextEdit(self.frame2)
        self.status.setEnabled(False)
        self.status.setGeometry(QtCore.QRect(160, 390, 311, 31))
        self.status.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.status.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setObjectName("status")
        self.pushButton = QtWidgets.QPushButton(self.frame2)
        self.pushButton.setGeometry(QtCore.QRect(200, 290, 31, 31))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 240, 31, 31))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 190, 31, 31))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 140, 31, 31))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/format-size.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 60, 31, 31))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/url.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.progressBar = QtWidgets.QProgressBar(self.frame2)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(220, 430, 161, 23))
        self.progressBar.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.DOWNLOAD = QtWidgets.QPushButton(self.frame2)
        self.DOWNLOAD.setGeometry(QtCore.QRect(60, 390, 91, 31))
        self.DOWNLOAD.setStyleSheet("QPushButton {\n"
"transition: all .5s ease;\n"
"color:white;\n"
"    font: 75 11pt \"Chilanka\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"border:1px solid white;\n"
"text-transform: uppercase;\n"
"text-align: center;\n"
"line-height: 1;\n"
"background-color :rgb(0, 119, 248);\n"
"\n"
"outline: none;  \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(24, 33, 62);\n"
"    background-color: white;;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.DOWNLOAD.setIconSize(QtCore.QSize(40, 40))
        self.DOWNLOAD.setObjectName("DOWNLOAD")
        self.youtube = QtWidgets.QPushButton(self.frame1)
        self.youtube.setEnabled(False)
        self.youtube.setGeometry(QtCore.QRect(20, 0, 121, 151))
        self.youtube.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/youtube (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.youtube.setIcon(icon5)
        self.youtube.setIconSize(QtCore.QSize(100, 100))
        self.youtube.setObjectName("youtube")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.URL.setPlaceholderText(_translate("MainWindow", "Video URL...."))
        self.SUBMIT.setText(_translate("MainWindow", "Submit"))
        self.title.setPlaceholderText(_translate("MainWindow", "Title"))
        self.views.setPlaceholderText(_translate("MainWindow", "Views"))
        self.length.setPlaceholderText(_translate("MainWindow", "Length"))
        self.rating.setPlaceholderText(_translate("MainWindow", "Video Rating"))
        self.status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.status.setPlaceholderText(_translate("MainWindow", "Download Status"))
        self.DOWNLOAD.setText(_translate("MainWindow", "Download"))
        self.SUBMIT.clicked.connect(self.submitc)
        self.DOWNLOAD.clicked.connect(self.downloadc)
    
    
    
    def submitc(self):
        self.link = self.URL.toPlainText()
        self.yt = YouTube(self.link)
        views = str(self.yt.views)
        length = str(self.yt.length)
        rating = str(self.yt.rating)
        #Showing details
        self.title.setText(self.yt.title)
        self.views.setText(views)
        self.length.setText(length)
        self.rating.setText(rating)
        #Getting the highest resolution possible
        self.ys = self.yt.streams.get_highest_resolution()
        
        
    def downloadc(self):
        #Starting download
        self.status.setText("Downloading...")
        self.ys.download()
        self.status.setText("Download completed!!")
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
