# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube
import math
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(0, 0, 881, 561))
        self.frame1.setAutoFillBackground(False)
        self.frame1.setStyleSheet("background-color: rgb(40, 43, 48);\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setGeometry(QtCore.QRect(170, 20, 691, 531))
        self.frame2.setAutoFillBackground(False)
        self.frame2.setStyleSheet("background-color: rgb(30, 32, 34);\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        Ui_MainWindow.URL = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.URL.setGeometry(QtCore.QRect(80, 60, 511, 31))
        Ui_MainWindow.URL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.URL.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.URL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.URL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        Ui_MainWindow.URL.setObjectName("URL")
        self.SUBMIT = QtWidgets.QPushButton(self.frame2)
        self.SUBMIT.setGeometry(QtCore.QRect(600, 60, 81, 31))
        self.SUBMIT.setStyleSheet("QPushButton {\n"
"transition: all .5s ease;\n"
"color:white;\n"
"    font: 75 11pt \"Chilanka\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"border:1px solid white;\n"
"text-transform: uppercase;\n"
"text-align: center;\n"
"line-height: 1;\n"
"background-color: rgb(62, 63, 67);\n"
"\n"
"outline: none;  \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(24, 33, 62);\n"
"    background-color: white;;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.SUBMIT.setIconSize(QtCore.QSize(40, 40))
        self.SUBMIT.setObjectName("SUBMIT")
        Ui_MainWindow.title = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.title.setEnabled(False)
        Ui_MainWindow.title.setGeometry(QtCore.QRect(80, 140, 511, 31))
        Ui_MainWindow.title.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.title.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.title.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.title.setUndoRedoEnabled(True)
        Ui_MainWindow.title.setObjectName("title")
        Ui_MainWindow.views = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.views.setEnabled(False)
        Ui_MainWindow.views.setGeometry(QtCore.QRect(80, 190, 151, 31))
        Ui_MainWindow.views.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.views.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.views.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.views.setObjectName("views")
        Ui_MainWindow.length = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.length.setEnabled(False)
        Ui_MainWindow.length.setGeometry(QtCore.QRect(80, 240, 141, 31))
        Ui_MainWindow.length.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.length.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.length.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.length.setObjectName("length")
        Ui_MainWindow.rating = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.rating.setEnabled(False)
        Ui_MainWindow.rating.setGeometry(QtCore.QRect(80, 290, 151, 31))
        Ui_MainWindow.rating.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.rating.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.rating.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.rating.setObjectName("rating")
        Ui_MainWindow.status = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.status.setEnabled(False)
        Ui_MainWindow.status.setGeometry(QtCore.QRect(310, 430, 181, 31))
        Ui_MainWindow.status.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.status.setStyleSheet("background-color: rgb(30, 32, 34);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.status.setPlaceholderText("")
        Ui_MainWindow.status.setObjectName("status")
        Ui_MainWindow.rating_button = QtWidgets.QPushButton(self.frame2)
        Ui_MainWindow.rating_button.setGeometry(QtCore.QRect(200, 290, 31, 31))
        Ui_MainWindow.rating_button.setStyleSheet("")
        Ui_MainWindow.rating_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_MainWindow.rating_button.setIcon(icon)
        Ui_MainWindow.rating_button.setIconSize(QtCore.QSize(25, 25))
        Ui_MainWindow.rating_button.setObjectName("rating_button")
        Ui_MainWindow.length_button = QtWidgets.QPushButton(self.frame2)
        Ui_MainWindow.length_button.setGeometry(QtCore.QRect(200, 240, 31, 31))
        Ui_MainWindow.length_button.setStyleSheet("")
        Ui_MainWindow.length_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_MainWindow.length_button.setIcon(icon1)
        Ui_MainWindow.length_button.setIconSize(QtCore.QSize(25, 25))
        Ui_MainWindow.length_button.setObjectName("length_button")
        Ui_MainWindow.views_button = QtWidgets.QPushButton(self.frame2)
        Ui_MainWindow.views_button.setGeometry(QtCore.QRect(200, 190, 31, 31))
        Ui_MainWindow.views_button.setStyleSheet("")
        Ui_MainWindow.views_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_MainWindow.views_button.setIcon(icon2)
        Ui_MainWindow.views_button.setIconSize(QtCore.QSize(25, 25))
        Ui_MainWindow.views_button.setObjectName("views_button")
        Ui_MainWindow.title_button = QtWidgets.QPushButton(self.frame2)
        Ui_MainWindow.title_button.setGeometry(QtCore.QRect(560, 140, 31, 31))
        Ui_MainWindow.title_button.setStyleSheet("")
        Ui_MainWindow.title_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/format-size.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_MainWindow.title_button.setIcon(icon3)
        Ui_MainWindow.title_button.setIconSize(QtCore.QSize(25, 25))
        Ui_MainWindow.title_button.setObjectName("title_button")
        self.url_button = QtWidgets.QPushButton(self.frame2)
        self.url_button.setEnabled(True)
        self.url_button.setGeometry(QtCore.QRect(560, 60, 31, 31))
        self.url_button.setStyleSheet("")
        self.url_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/url.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.url_button.setIcon(icon4)
        self.url_button.setIconSize(QtCore.QSize(25, 25))
        self.url_button.setObjectName("url_button")
        self.DOWNLOAD = QtWidgets.QPushButton(self.frame2)
        self.DOWNLOAD.setGeometry(QtCore.QRect(150, 430, 151, 31))
        self.DOWNLOAD.setStyleSheet("QPushButton {\n"
"transition: all .5s ease;\n"
"color:white;\n"
"    font: 75 11pt \"Chilanka\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"border:1px solid white;\n"
"text-transform: uppercase;\n"
"text-align: center;\n"
"line-height: 1;\n"
"background-color: rgb(62, 63, 67);\n"
"\n"
"outline: none;  \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(24, 33, 62);\n"
"    background-color: white;;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/download (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DOWNLOAD.setIcon(icon5)
        self.DOWNLOAD.setIconSize(QtCore.QSize(25, 25))
        self.DOWNLOAD.setObjectName("DOWNLOAD")
        Ui_MainWindow.patharea = QtWidgets.QTextEdit(self.frame2)
        Ui_MainWindow.patharea.setEnabled(False)
        Ui_MainWindow.patharea.setGeometry(QtCore.QRect(80, 340, 401, 31))
        Ui_MainWindow.patharea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Ui_MainWindow.patharea.setStyleSheet("background-color: rgb(62, 63, 67);\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.patharea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.patharea.setUndoRedoEnabled(True)
        Ui_MainWindow.patharea.setObjectName("patharea")
        self.path_button = QtWidgets.QPushButton(self.frame2)
        self.path_button.setGeometry(QtCore.QRect(430, 340, 51, 31))
        self.path_button.setStyleSheet("QPushButton {\n"
"transition: all .5s ease;\n"
"color:white;\n"
"    font: 75 11pt \"Chilanka\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"text-transform: uppercase;\n"
"text-align: center;\n"
"line-height: 1;\n"
"background-color: rgb(30, 32, 34);\n"
"\n"
"outline: none;  \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(24, 33, 62);\n"
"    background-color: white;;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.path_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/folder (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.path_button.setIcon(icon6)
        self.path_button.setIconSize(QtCore.QSize(25, 25))
        self.path_button.setObjectName("path_button")
        self.youtube = QtWidgets.QPushButton(self.frame1)
        self.youtube.setEnabled(False)
        self.youtube.setGeometry(QtCore.QRect(20, 0, 121, 151))
        self.youtube.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/youtube (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.youtube.setIcon(icon7)
        self.youtube.setIconSize(QtCore.QSize(100, 100))
        self.youtube.setObjectName("youtube")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        Ui_MainWindow.statusbar = QtWidgets.QStatusBar(MainWindow)
        Ui_MainWindow.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(Ui_MainWindow.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        Ui_MainWindow.URL.setPlaceholderText(_translate("MainWindow", "Video URL...."))
        self.SUBMIT.setText(_translate("MainWindow", "Submit"))
        Ui_MainWindow.title.setPlaceholderText(_translate("MainWindow", "Title"))
        Ui_MainWindow.views.setPlaceholderText(_translate("MainWindow", "Views"))
        Ui_MainWindow.length.setPlaceholderText(_translate("MainWindow", "Length"))
        Ui_MainWindow.rating.setPlaceholderText(_translate("MainWindow", "Video Rating"))
        Ui_MainWindow.status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.DOWNLOAD.setText(_translate("MainWindow", "Download"))
        Ui_MainWindow.patharea.setPlaceholderText(_translate("MainWindow", "Path "))
        
        

